/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.proUi.cmd.ServerUi.Panel.Groups;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import main.Ui;
import org.proUi.cmd.ServerUi.Panel.PerPanel;

/**
 *
 * @author Administrator
 */
public class NewG extends javax.swing.JFrame {

    private PerPanel perp;
    private String worldName;
    private List<String> worlded = new ArrayList<>();

    /**
     * Creates new form NewG
     */
    public NewG() {
        initComponents();
                new Ui().addClassUi(this);
    }

    /**
     *
     * @param group 这个组将在哪个世界内创造。
     * @param grouped 这个世界内有其他哪些组的名字
     * @param p 权限窗口传递过来，我要使用你的方法在等下。 务必仔细查看本方法使用参数，否则将一去不复返。！
     */
    public NewG(String group, List<String> grouped, PerPanel p) {
        this.perp = p;
        this.worlded = grouped;
        this.worldName = group;
        initComponents();
        //jTextArea1

        for (int i = 0; i < perp.getDefaultListModel1().size(); i++) {
            jTextArea1.append(perp.getDefaultListModel1().getElementAt(i) + "\n");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        t1 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        g1 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        g2 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("创建一个权限组");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "创建权限组", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("微软雅黑", 0, 14), java.awt.Color.black)); // NOI18N
        jPanel3.setToolTipText("全局权限组设置");
        jPanel3.setOpaque(false);

        jLabel7.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        jLabel7.setText("本权限组名字：");

        jLabel8.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        jLabel8.setText("本组继承的权限组(inheritance): ");

        jLabel9.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        jLabel9.setText("本组其他指定权限(permissions):");

        jLabel11.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        jLabel11.setText("<html>是否为default？ <br> - 所有权限组只能有一个为default,这是玩家的初始组</html>");

        jLabel12.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        jLabel12.setText("本组玩家是否可建筑/破坏？");

        jLabel13.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        jLabel13.setText("本组玩家称号名称设置：");

        jLabel14.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel14.setText("前缀：");

        jLabel15.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel15.setText("后缀：");

        t2.setFont(new java.awt.Font("新宋体", 0, 12)); // NOI18N
        t2.setText("&2");

        t3.setFont(new java.awt.Font("楷体", 0, 12)); // NOI18N

        jButton1.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jButton1.setText("保存本组设置");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jButton2.setText("放弃本组设置");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jCheckBox1.setText("是(谨慎修改)");
        jCheckBox1.setOpaque(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jCheckBox2.setText("是(谨慎修改)");
        jCheckBox2.setOpaque(false);

        t1.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        t1.setText("MyGroup");

        g1.setColumns(20);
        g1.setFont(new java.awt.Font("宋体", 0, 13)); // NOI18N
        g1.setRows(5);
        g1.setText("default\ng:essentials_builder\ng:towny_builder");
        jScrollPane7.setViewportView(g1);

        g2.setColumns(20);
        g2.setFont(new java.awt.Font("宋体", 0, 13)); // NOI18N
        g2.setRows(5);
        jScrollPane8.setViewportView(g2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t1))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jCheckBox1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t3)))
                .addContainerGap())
            .addComponent(jScrollPane8)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13)
                    .addComponent(jLabel9))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane7)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(7, 7, 7))
        );

        jLabel10.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        jLabel10.setText("您或许想继承这里的某些组？");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("黑体", 0, 13)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("楷体", 0, 12)); // NOI18N
        jLabel1.setText("来自: 全局权限组");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel1))
                        .addGap(0, 46, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //在下面
        /*     * 
         * @param name  本权限组名字，标准字体文字
         * @param inheritance   本组继承了哪些组
         * @param permissions   本组扩展了哪些权限
         * @param prefix    本组的名字前戳  
         * @param suffix    本组的名字后缀
         * @param defaults  本组是否为一个默认组？只能有一个组是属于默认组。
         * @param builder   本组是否允许建筑/破坏地形？
         * @param worldName  本组将放置在哪个世界内，不可重复名，但应该已处于检查完毕。
         * 使用务必小心。*/

        for (String s : this.worlded) {
            if (s.equalsIgnoreCase(t1.getText())) {
                JOptionPane.showMessageDialog(null,
                        "权限组名字不能和已经有的权限组名字重名,请换个名字~", "信息", JOptionPane.INFORMATION_MESSAGE);
                System.out.println("[异常] 有重复的世界名字！");
                return;
            }
        }
        String[] tmp = g1.getText().split("\n");
        String[] tmp2 = g2.getText().split("\n");
        List<String> list = new ArrayList<>();
        List<String> list2 = new ArrayList<>();
        for (String ee : tmp) {
            list.add(ee);
        }
        for (String ee : tmp2) {
            list2.add(ee);
        }/*
         * @param path 保存的文件路径，例如取运行目录（）+“\YAME.yaml”
         * @param name 本权限组名字，标准字体文字
         * @param inheritance 本组继承了哪些组
         * @param permissions 本组扩展了哪些权限
         * @param prefix 本组的名字前戳
         * @param suffix 本组的名字后缀
         * @param defaults 本组是否为一个默认组？只能有一个组是属于默认组。
         * @param builder 本组是否允许建筑/破坏地形？*/

        String path = main.Main.yunStr + "/plugins/GroupManager/worlds/" + worldName + "/groups.yml";
        new Group().SaveGroups(path, t1.getText().toString(), list, list2,
                t2.getText().toString(), t3.getText().toString(), jCheckBox1.isSelected(), jCheckBox2.isSelected());
        // this.dispose();
        // this.perp.addGroups(t1.getText(), tmp, tmp2, t2.getText(), t3.getText(), jCheckBox1.isSelected(), jCheckBox2.isSelected(), worldName);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea g1;
    private javax.swing.JTextArea g2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    // End of variables declaration//GEN-END:variables
}
