/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.io.File;
import javax.swing.JOptionPane;
import org.proUi.cmd.ServerUi.Panel.PerPanel;

/**
 *
 * @author Administrator
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        PerPanel pe = new PerPanel();
        initComponents();
        new Ui().addClassUi(this);
        if(!ifFile("/plugins/GroupManager/globalgroups.yml")){
            tishi2.setText("很抱歉！您无法使用本编辑器.\n因为我们无法在您的Minecraft服务器中检测到 "+System.getProperty("user.dir") + 
                    "/plugins/GroupManager/globalgroups.yml 文件\n  可能是因为您未安装 Essentials基础插件和GroupManager权限管理插件的缘故。\n"
                    + "     解决方法: 尝试安装Essentials基础插件和GroupManager权限管理插件，并重启服务器，再使用本程序");
             JOptionPane.showMessageDialog(null,
 "未检测到配置文件，运行失败！请查看具体信息！", "系统信息", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!ifFile("/plugins/GroupManager/config.yml")){
            tishi2.setText("很抱歉！您无法使用本编辑器.\n因为我们无法在您的Minecraft服务器中检测到 "+System.getProperty("user.dir") + 
                    "/plugins/GroupManager/config.yml 文件\n    可能是因为您未安装 Essentials基础插件和GroupManager权限管理插件的缘故。\n"
                    + "     解决方法: 尝试安装Essentials基础插件和GroupManager权限管理插件，并重启服务器，再使用本程序");
                         JOptionPane.showMessageDialog(null,
 "未检测到配置文件，运行失败！请查看具体信息！", "系统信息", JOptionPane.ERROR_MESSAGE);
            return;
        }
        jLabel7.setText("检测完毕√: 您的Minecraft服务器支持本编辑器编辑权限，您可以正常使用！");
        jLabel7.setForeground(Color.GREEN);
        tishi2.setText("所需文件存在√\n请确保您的Essentials基础插件套集正常运行，本插件将编辑GroupManager权限管理插件的配置文件。\n强烈建议您在服务器关闭之后编辑。编辑完毕之后必须重新启动服务器！");
        
        
        jTabbedPane1.add("权限编辑器", pe);
    }
    
    private boolean ifFile(String str){//相对路径   /XXX/XXX .JAR
        File file = new File(System.getProperty("user.dir") + str);
        if(file.exists()){
             return true;
        }else{
             return false;
        }
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tishi2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Suwings Permissions 编辑器 - Version 1.0.1");
        setFont(new java.awt.Font("微软雅黑", 0, 10)); // NOI18N

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        jLabel1.setText("Suwings Permissions 编辑器软件\n");

        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 10)); // NOI18N
        jLabel2.setText("Version 1.0.1");

        jLabel3.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jLabel3.setText("|____     轻松的编辑和管理你的Minecraft服务器权限组");

        jLabel4.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel4.setText("Suwings Permissions 编辑器程序开发者:  双羽 && C△Y && 竹子");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/2.jpg"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel8.setText("|____     如果您对本程序有任何建议请务必发送邮件，我们会十分感谢您的来信： emailwk@qq.com");

        jLabel6.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        jLabel6.setText("注意: 本程序需要Minecraft服务器安装了Essentials基础插件和GroupManager权限管理插件才可以运行，并且在运行本程序之前必须保证您的服务端已经生成配置文件。");

        jLabel7.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("|____     很抱歉！我们的编辑器无法支持当前您的Minecraft服务器，请具体查看下列信息：");

        tishi2.setColumns(20);
        tishi2.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        tishi2.setRows(5);
        jScrollPane1.setViewportView(tishi2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4))
                        .addComponent(jLabel6)))
                .addGap(0, 214, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(37, 37, 37)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("首页", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea tishi2;
    // End of variables declaration//GEN-END:variables
}
